### ISSUE TITLE
Improve level loading system

### ISSUE THREAD

**Issue by owalk** [Sean-Nishi/Reluctant-Hero#152]
- [x] Refactor level out of game #207
- [x] implement level manager #206
- [x] Refactor camera manager into level manager #209
- [x] Refactor music manager #208
- [x] loading generic level #210
- [x] handling pause menu #152
- [x] handling main menu #211
- [x] add start screen #29
