### ISSUE TITLE
Update repo documentation/var naming

### ISSUE THREAD

**Issue by owalk** [Sean-Nishi/Reluctant-Hero#212]
- [x] Update Entity docs #283 
- [x] skeleton docs #213
- [x] player docs #214
- [x] damsel docs #215
- [x] npc docs #216
- [x] tile docs #217
- [x] all manager docs #218
- [x] game docs #219
- [x] all terrain docs #220
- [x] update landing readme #222
- [x] update about section #223
- [x] character docs #282 
- [x] restructure file hierarchy #284 
- [x] remove legacy terrain code #287 
- [x] update spriteSheet.py docs and add typehints #298 
- [x] update support.py docs and add type hints #299
